trunk/DMP/DMP/Controllers/DealerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMP.Models;
using DMP.ModelsView;
using DMP.Repository;
using DMP.Services;
using DMP.Services.Interface;
using OfficeOpenXml;
using Target = DMP.ModelsView.Target;

namespace DMP.Controllers {

    [Authorize]
    public class DealerController : Controller {

        private readonly IDealerManpowerService manpowerService;
        private readonly IUserService userService;
        private readonly IProfileService profileService;
        private readonly IMasterService masterService;
        private readonly ICompetencyProfileMapService competencyProfileMapService;
        private readonly ITrainingProfileMapService trainingProfileMapService;
        private readonly IAttritionProfileMapService attritionProfileMapService;
        private readonly IDealerManpowerTargetService manpowerTargetService;
        private readonly IUserDealerMapService userDealerMapServiceService;
        private readonly ITargetService targetService;
        private readonly IManpowerSalaryService salaryService;
        private readonly IDealerManpowerService dealerManpowerService;
        private readonly IDsmDseTargetMapService dsmDseTargetMapService;

        public DealerController(IDealerManpowerService manpowerService, IUserService userService, IProfileService profileService, IMasterService masterService, ICompetencyProfileMapService competencyProfileMapService, ITrainingProfileMapService trainingProfileMapService, IAttritionProfileMapService attritionProfileMapService, IDealerManpowerTargetService manpowerTargetService, IUserDealerMapService userDealerMapServiceService, ITargetService targetService, IManpowerSalaryService salaryService, IDealerManpowerService dealerManpowerService, IDsmDseTargetMapService dsmDseTargetMapService) {
            this.manpowerService = manpowerService;
            this.userService = userService;
            this.profileService = profileService;
            this.masterService = masterService;
            this.competencyProfileMapService = competencyProfileMapService;
            this.trainingProfileMapService = trainingProfileMapService;
            this.attritionProfileMapService = attritionProfileMapService;
            this.manpowerTargetService = manpowerTargetService;
            this.userDealerMapServiceService = userDealerMapServiceService;
            this.targetService = targetService;
            this.salaryService = salaryService;
            this.dealerManpowerService = dealerManpowerService;
            this.dsmDseTargetMapService = dsmDseTargetMapService;
            if (System.Web.HttpContext.Current.Session["BreadcrumbList"] == null) {
                System.Web.HttpContext.Current.Session["BreadcrumbList"] = new List<BreadcrumbModel>();
            }
        }

        #region ManpowerTarget

        [Authorize(Roles = "HQ,HQR")]
        public ActionResult ManpowerTargets() {
            Session["BreadcrumbList"] = Utils.HtmlExtensions.SetBreadcrumbs((List<BreadcrumbModel>)Session["BreadcrumbList"], "/Dealer/ManpowerTargets", "Manpower");
            var currentDate = DateTime.Now.Date;
            var month = masterService.FindAndCreateMonth(currentDate.ToString("MMMM"), currentDate.Year);
            var products = masterService.GetAllProducts().OrderBy(x => x.Id);
            var monthList = masterService.GetAllFinancialMonths(currentDate.ToString("MMMM"), currentDate.Year).Select(x => new KeyValuePair<int, string>(x.Id, string.Format("{0}-{1}", x.Name, x.Year))).ToList();
            var model = new ManpowerTargetViewModel {
                MonthId = month.Id,
                MonthName = string.Format("{0} - {1}", month.Name, month.Year),
                TargetPlans = new List<ManpowerTargetPlanModel>(),
                Products = products.Select(x => new KeyValuePair<int, string>(x.Id, x.Name)),
                Months = monthList,
                Users = userService.FindUsers(x => x.Role == "CSM").Select(x => new KeyValuePair<int, string>(x.Id, x.Name)).ToList()
            };
            ViewBag.List = Session["BreadcrumbList"];
            return View(model);
        }

        [Authorize(Roles = "HQ")]
        public ActionResult SaveMnpowerTargets(ManpowerTargetViewModel model) {
            var csmId = model.CsmId;
            var monthId = model.MonthId;
            foreach (var target in model.TargetPlans) {
                var dealerId = target.DealerId;
                foreach (var plan in target.Targets) {
                    var manpowerTarget = ManpowerTargetPlanModel.ToDomainModel(plan);
                    manpowerTarget.UserId = csmId;
                    manpowerTarget.DealerId = dealerId;
                    manpowerTarget.MonthId = monthId;
                    if (manpowerTarget.Id > 0) {
                        manpowerTargetService.UpdateDealerManpowerTarget(manpowerTarget);
                    } else {
                        manpowerTargetService.AddDealerManpowerTarget(new[] { manpowerTarget });
                    }
                }
            }
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "HQ")]
        public ActionResult GetManpowerTargets(int monthId, int csmId) {
            var month = masterService.GetMonth(monthId);
            var currentDate = DateTime.Now;
            var currentMonth = masterService.FindAndCreateMonth(currentDate.ToString("MMMM"), currentDate.Year);
            var selectedDate = new DateTime(month.Year, masterService.GetMonthIndex(month.Name), 1);
            if (currentDate.Date < selectedDate.Date) {
                var futureTargets = manpowerTargetService.FindDealerManpowerTargets(x => x.MonthId == month.Id);
                if (!futureTargets.Any()) {
                    var targets = manpowerTargetService.FindDealerManpowerTargets(x => x.MonthId == currentMonth.Id);
                    if (targets.Any()) {
                        foreach (var target in targets) {
                            target.MonthId = month.Id;
                        }
                        manpowerTargetService.AddDealerManpowerTarget(targets);
                    }
                }
            }
            var products = masterService.GetAllProducts().OrderBy(x => x.Id);
            var dealers = userDealerMapServiceService.FindUserDealerMaps(x => x.UserId == csmId).Select(x => x.Dealer);
            var data = manpowerTargetService.FindDealerManpowerTargets(x => x.UserId == csmId && x.MonthId == month.Id).ToList();
            var list = new List<ManpowerTargetPlanModel>();
            foreach (var dealer in dealers) {
                var tempModel = new ManpowerTargetPlanModel {
                    DealerId = dealer.Id,
                    Dealer = dealer.Name
                };
                var targetList = new List<ManpowerProductTargetModel>();
                foreach (var product in products) {
                    var all = data.Where(x => x.DealerId == dealer.Id && x.ProductId == product.Id);
                    var total = all.Sum(x => x.Planned);
                    targetList.Add(new ManpowerProductTargetModel {
                        ProductId = product.Id,
                        Planned = total,
                        Id = all.Any() ? all.First().Id : 0
                    });
                }
                tempModel.Targets = targetList;
                list.Add(tempModel);
            }
            var mnthName = string.Format("{0} - {1}", month.Name, month.Year);
            return Json(new { success = true, targetPlan = list, monthName = mnthName }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region ManpowerProfile

        public ActionResult ManpowerProfile(int id, int dealerId) {
            Session["BreadcrumbList"] = Utils.HtmlExtensions.SetBreadcrumbs((List<BreadcrumbModel>)Session["BreadcrumbList"], string.Format("/Dealer/ManpowerProfile/{0}", id), "Profile");
            var csm = userService.GetUserByUserName(User.Identity.Name);
            var model = new CsmDealerViewModel {
                Manpower = id > 0 ? DealerManpowerModel.FromDomainModel(manpowerService.GetDealerManpower(id)) : new DealerManpowerModel(),
                Designations = Enumeration.GetAll<Designation>(),
                TrainingLevels = Enumeration.GetAll<TrainingLevel>(),
                Attrition = new AttritionProfileModel(),
                Training = new TrainingProfileModel(),
                Attritions = masterService.GetAllAttritions().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)),
                AllTrainings = masterService.GetAllTrainings().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)),
                Products = masterService.GetAllProducts().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)).ToList()
            };
            model.Manpower.DealerId = dealerId;
            model.Manpower.UserId = csm.Id;
            ViewBag.List = Session["BreadcrumbList"];
            return View(model);
        }

        [HttpPost]
        public ActionResult SaveManpower(CsmDealerViewModel model) {
            var profile = DealerManpowerModel.ToProfileDomain(model.Manpower);
            var manpower = DealerManpowerModel.ToManpowerDomain(model.Manpower);
            profile.DealerManpower = manpower;

            if (profile.Id > 0) {
                profileService.UpdateProfile(profile);
                dealerManpowerService.UpdateDealerManpower(manpower);
            } else {
                profileService.AddProfile(new[] { profile });
            }

            //Add Salary
            if (model.Manpower.Salary > 0) {
                salaryService.AddManpowerSalary(new[]{new ManpowerSalary

trunk/DMP/DMP/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMP.Models;
using DMP.ModelsView;
using DMP.Utils;

namespace DMP.Controllers {
    public class ReportingController : Controller {


        public ActionResult MonthWisePlanAndActual(IEnumerable<Target> targets) {
            var groupedTargetMonth = targets.GroupBy(x => x.Month);
            BarTargetModels model = new BarTargetModels();
            model.Models = groupedTargetMonth.Select(
               x => new BarTargetModel { Month = x.Key, T1 = x.Sum(y => y.T1), T2 = x.Sum(y => y.T2), Actual = x.Sum(y => y.Actual) }).ToList();
            var months=model.Models.Select(x => x.Month);
            var actuals=model.Models.Select(x => x.Actual);
            var t1=model.Models.Select(x => x.T1);
            var t2=model.Models.Select(x => x.T2);
            var Serializer=new System.Web.Script.Serialization.JavaScriptSerializer();
            ViewBag.months=Serializer.Serialize(months);
            ViewBag.actuals=Serializer.Serialize(actuals);
            ViewBag.t1 = Serializer.Serialize(t1);
            ViewBag.t2 = Serializer.Serialize(t2);
            return PartialView("MonthWisePlanAndActual");
        }

    }
}

trunk/DMP/DMP/Views/Dealer/AttritionPartial.cshtml
@model DMP.ModelsView.AttritionProfileViewModel
<script type="text/javascript">
    $(document).ready(function () {
        $('.datetime').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "dd-MM-yy"
        });
    });
</script>
<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnComplete = "closePopUp()" })) {
        @Html.HiddenFor(x => x.ProfileId)
        <div style="width: 100%">
            <table class="twelve">
                <tbody>
                    <tr>
                        <td>@Html.LabelFor(x => x.Attrition.AttritionId)
                        </td>
                        <td>@Html.DropDownListFor(x => x.Attrition.AttritionId, new SelectList(Model.Attritions, "Key", "Value"), new { @class = "custom dropdown", @style = "margin-bottom:10px" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(x => x.Attrition.DOLString)
                        </td>
                        <td>
                            @Html.TextBoxFor(x => x.Attrition.DOLString, new { @class = "datetime" })
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2" style="text-align: right">
                            <input type="submit" value="Save"  class="btn btn-primary"  />
                            <input type="reset" value="Clear"  class="btn btn-primary"  />
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    }
</div>

trunk/DMP/DMP/Views/Dealer/ManpowerProfile.cshtml
@model DMP.ModelsView.CsmDealerViewModel
@using DMP.Utils
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="/assets/plugins/fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet"
    type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Assets/plugins/fancybox/jquery.mousewheel-3.0.4.pack.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Assets/plugins/fancybox/jquery.fancybox-1.3.4.pack.js")" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $.ajaxSetup({ cache: false });
        setFancyboxUrl();

        $('.datetime').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "dd-MM-yy"
        });

        //        $('#manpowerForm').submit(function (e) {
        //            //            if (!$(this).valid()) {
        //            //                e.preventDefault();
        //            //                return false;
        //            //            }
        //            $.ajax({
        //                url: '/Dealer/SaveManpower',
        //                type: 'POST',
        //                dataType: 'json',
        //                data: JSON.stringify(ko.mapping.toJS(viewModel)),
        //                contentType: 'application/json; charset=utf-8',
        //                success: function (data) {
        //                    if (data.success && data.manpower != null) {
        //                        //                        ko.mapping.updateFromJS(viewModel.Manpower, ko.mapping.toJS(data.manpower));
        //                        //                        viewModel.resetManpower();
        //                        var url = '/Dealer/DseProfile/' + Manpower.Id();
        //                        window.location.href = url;
        //                    }
        //                    //                    viewModel.resetManpower();
        //                }
        //            });
        //            return false;
        //        });

        $('#linkAddDse').bind('click', function () {
            $('#dvManpowers').hide();
            $('#dvManpowerForm').show();
        });
        $('#linkMnanageDse').bind('click', function () {
            $('#dvManpowerForm').hide();
            $('#dvManpowers').show();
        });

        function setFancyboxUrl() {
            var id = @(Model.Manpower.Id);
            if (id > 0) {
                
                $('#linkCompetency').attr('href', '/Dealer/Competency/' + id);
                $('#linkTraining').attr('href', '/Dealer/Training/' + id);
                $('#linkAttrition').attr('href', '/Dealer/Attrition/' + id);
            }
        }
        $('#linkTrainingDisplay').bind('click', function () {
            if ($('#trainingDisplayRow').is(':visible')) {
                $('#trainingDisplayRow').hide('slow');
                $(this).text('Training +');
            } else {
                $('#trainingDisplayRow').show('slow');
                $(this).text('Training -');
            }
        });
        $('#linkCompetency').fancybox({
            'padding': '25px',
            'autoScale': true,
            'scrolling': 'no',
            'easingIn': 'swing',
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'type': 'ajax',
            'centerOnScroll': true,
            'overlayShow': true,
            'enableEscapeButton': false,
            'hideOnOverlayClick': false,
            'title': 'Competency',
            'onClosed': function () {
            }
        });
        $('#linkTraining').fancybox({
            'padding': '25px',
            'autoScale': true,
            'scrolling': 'no',
            'easingIn': 'swing',
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'type': 'ajax',
            'centerOnScroll': true,
            'overlayShow': true,
            'enableEscapeButton': false,
            'hideOnOverlayClick': false,
            'title': 'Training',
            'onClosed': function () {
            }
        });
        $('#linkAttrition').fancybox({
            'padding': '25px',
            'autoScale': true,
            'scrolling': 'no',
            'easingIn': 'swing',
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'type': 'ajax',
            'centerOnScroll': true,
            'overlayShow': true,
            'enableEscapeButton': false,
            'hideOnOverlayClick': false,
            'title': 'Attrition',
            'onClosed': function () {
            }
        });
    });
</script>
<div class="row-fluid">
    <div class="span10 offset1" id="dvEditProfile">
        <legend>Profile Information</legend>
        @using (Html.BeginForm("SaveManpower", "Dealer", FormMethod.Post, new { @id = "manpowerForm" })) {
            @Html.HiddenFor(x => x.Manpower.Id)
            @Html.HiddenFor(x => x.Manpower.UserId)
            @Html.HiddenFor(x => x.Manpower.DealerId)
            @Html.HiddenFor(x => x.Manpower.ProfileId)
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.Name)
                @Html.TextBoxFor(x => x.Manpower.Name, new { @id = "txtManpowerName" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.Type)
                @Html.DropDownListFor(x => x.Manpower.Type, new SelectList(Model.Designations, "Value", "Value"))
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.DOBString)
                @Html.TextBoxFor(x => x.Manpower.DOBString, new { @class = "datetime" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.ContactNumber)
                @Html.TextBoxFor(x => x.Manpower.ContactNumber, new { @id = "txtManpowerPhone" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.Email)
                @Html.TextBoxFor(x => x.Manpower.Email, new { @id = "txtManpowerEmail" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.Address)
                @Html.TextBoxFor(x => x.Manpower.Address, new { @id = "txtManpowerAddress" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.PANNumber)
                @Html.TextBoxFor(x => x.Manpower.PANNumber, new { @id = "txtManpowerPan" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.ProductId)
                @Html.DropDownListFor(x => x.Manpower.ProductId, new SelectList(Model.Products, "Key", "Value"))
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.SAPId)
                @Html.TextBoxFor(x => x.Manpower.SAPId, new { @id = "txtSapId" })
            </div>
            
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.DOJString)
                @Html.TextBoxFor(x => x.Manpower.DOJString, new { @class = "datetime" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.TotalWorkExperience)
                @Html.TextBoxFor(x => x.Manpower.TotalWorkExperience, new { @id = "txtManpowerTotalWorkExperience" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.ExperienceWithVE)
                @Html.TextBoxFor(x => x.Manpower.ExperienceWithVE, new { @id = "txtManpowerExperienceWithVE" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.TrainingLevel)
                @Html.DropDownListFor(x => x.Manpower.TrainingLevel, new SelectList(Model.TrainingLevels, "Value", "Value"))
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.TIVRepresenting)
                @Html.TextBoxFor(x => x.Manpower.TIVRepresenting, new { @id = "txtManpowerTIVRepresenting" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.AreaRepresenting)
                @Html.TextBoxFor(x => x.Manpower.AreaRepresenting, new { @id = "txtManpowerAreaRepresenting" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.PreviousCompany)
                @Html.TextBoxFor(x => x.Manpower.PreviousCompany, new { @id = "txtManpowerPreviousCompany" })
            </div>
            <div class="span3">
                @Html.LabelFor(x => x.Manpower.PreviousJobProfile)
                @Html.TextBoxFor(x => x.Manpower.PreviousJobProfile, new { @id = "txtManpowerPreviousJobProfile" })
            </div>
            <div class="row">
            </div>
            if (Model.Manpower.Id > 0) {
            <div class="span3">
                <a href="#" id="linkCompetency">Competency</a>
            </div>
            <div class="span3">
                <a href="#" id="linkTraining">Other Trainings</a>
            </div>
            <div class="span3">
                <a href="#" id="linkAttrition">Remove DSE/DSM</a>
            </div>
            }
            <div class="span6">
                <input type="submit" value="Save" class="btn btn-primary" />
                <input type="reset" value="Reset" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

trunk/DMP/DMP/Views/Dealer/ManpowerTargets.cshtml
@model DMP.ModelsView.ManpowerTargetViewModel
@using DMP.Utils
@{
    ViewBag.Title = "Manpower";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    var TargetPlans = ko.mapping.fromJS(@Html.Raw(Html.ToJSON(Model.TargetPlans)));
    var Products = ko.mapping.fromJS(@Html.Raw(Html.ToJSON(Model.Products)));
    var CsmId = ko.mapping.fromJS(@Html.Raw(Html.ToJSON(Model.CsmId)));
    var MonthId = ko.mapping.fromJS(@Html.Raw(Html.ToJSON(Model.MonthId)));
    var MonthName = ko.mapping.fromJS(@Html.Raw(Html.ToJSON(Model.MonthName)));
</script>
<script type="text/javascript">
    var viewModel = {
        TargetPlans: TargetPlans,
        Products: Products,
        CsmId: CsmId,
        MonthId: MonthId,
        MonthName: MonthName
    };

    viewModel.resetTarget = function (data) {
        var monthId = $('#ddlMonth').val();
        if (monthId == viewModel.MonthId()) {
            $('.display').each(function () {
                $(this).hide();
            });
            $('.editInput').each(function () {
                $(this).show();
            });
            $('#dvSubmit').show();
        } else {
            $('.editInput').each(function () {
                $(this).hide();
            });
            $('.display').each(function () {
                $(this).show();
            });
            $('#dvSubmit').hide();
            $('#linkEdit').hide();
        }
    };

    $(document).ready(function () {
        ko.applyBindings(viewModel);

        $('#linkEdit').bind('click', function () {
            $('.display').each(function () {
                $(this).hide();
            });
            $('.editInput').each(function () {
                $(this).show();
            });
            $('#dvSubmit').show();
            $('#linkEdit').hide();
        });

        $('#targetForm').submit(function (e) {
            //            if (!$(this).valid()) {
            //                e.preventDefault();
            //                return false;
            //            }
            $.ajax({
                url: '/Dealer/SaveMnpowerTargets',
                type: 'POST',
                dataType: 'json',
                data: JSON.stringify(ko.mapping.toJS(viewModel)),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    if (data.success) {
                        $('.editInput').each(function () {
                            $(this).hide();
                        });
                        $('.display').each(function () {
                            $(this).show();
                        });
                        $('#dvSubmit').hide();
                        $('#linkEdit').show();
                    }
                }
            });
            return false;
        });

        $('#ddlMonth').bind('change', function () {
            loadTargets();
        });
        $('#ddlCsm').bind('change', function () {
            loadTargets();
        });

        function loadTargets() {
            var monthId = $('#ddlMonth').val();
            var csmId = $('#ddlCsm').val();
            if (monthId > 0 && csmId > 0) {
                $.post("/Dealer/GetManpowerTargets", { monthId: monthId, csmId: csmId }, function (res) {
                    if (res.success && res.targetPlan != null) {
                        ko.mapping.updateFromJS(viewModel.TargetPlans, ko.mapping.toJS(res.targetPlan));
                        ko.mapping.updateFromJS(viewModel.MonthName, ko.mapping.toJS(res.monthName));
                        $('#tblTargetPlan').trigger('update');
                        $('#linkMonthName').trigger('update');
                        viewModel.resetTarget();
                    }
                });
            }
        }
    });
</script>
<script type="text/html" id="manpowerTargetTemplate">
    <tr>
        <td><input type="hidden" data-bind="value: DealerId"/><span data-bind="text: Dealer"/></td>
        {{each(i,target) Targets}}
        <td><input type="hidden" data-bind="value: target.Id"/><input type="hidden" data-bind="value: target.ProductId"/><span class="display" data-bind="text: target.Planned"/><input style="display:none" class="editInput input-micro-mini" type="Text" data-bind="value: target.Planned"/></td>
        {{/each}}
    </tr>
</script>
<div class="row-fluid">
    <div class="span9 offset2" style="text-align: center !important;">
        <h3 data-bind="text: MonthName">
        </h3>
        <hr />
    </div>
</div>
<div class="row-fluid">
    @using (Html.BeginForm("SaveMnpowerTargets", "Dealer", FormMethod.Post, new { @id = "targetForm" })) {
        <div class="span8 offset3 text-align-right">
            <div style="display: inline-block">
                Month
                @Html.DropDownListFor(x => x.MonthId, new SelectList(Model.Months, "Key", "Value"), "Select Month", new { @id = "ddlMonth" })
            </div>
            <div style="display: inline-block">
                CSM
                @Html.DropDownListFor(x => x.CsmId, new SelectList(Model.Users, "Key", "Value"), "Select Csm", new { @id = "ddlCsm", data_bind = "value:CsmId" })
            </div>
        </div>
       
        <div class="span9 offset2">
            <table class="table table-bordered" id="tblTargetPlan">
                <thead>
                    <tr>
                        <th colspan=@(Model.Products.Count()) class="head1">
                            Manpower Plan
                        </th>
                        <th class="head1 text-align-right">
                            <a href="#" id="linkEdit" class="edit" style="display: none" title="click here to edit current month target">
                            </a>
                        </th>
                    </tr>
                    <tr>
                        <th class="head2">
                            Dealers
                        </th>
                        @foreach (var product in Model.Products) {
                            <th class="head2">@product.Value
                            </th>
                        }
                    </tr>
                </thead>
                <tbody data-bind='template :{name:"manpowerTargetTemplate",foreach:TargetPlans}'>
                </tbody>
            </table>
            <div id="dvSubmit" class="text-align-right">
                <input type="submit" value="Update" class="btn btn-primary" />
                <input type="reset" value="Cancel" data-bind="click: resetTarget" class="btn btn-primary" />
            </div>
        </div>  
    }
</div>

trunk/DMP/DMP/Views/Dealer/TrainingPartial.cshtml
@model DMP.ModelsView.TrainingProfileViewModel
<script type="text/javascript">
    $(document).ready(function () {
        $('.datetime').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "dd-MM-yy"
        });
    });
</script>
<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnComplete = "closePopUp()" })) {
        @Html.HiddenFor(x => x.ProfileId)
        <div style="width: 100%">
            <table class="twelve">
                <tbody>
                    <tr>
                        <td>@Html.LabelFor(x => x.Training.TrainingId)
                        </td>
                        <td>@Html.DropDownListFor(x => x.Training.TrainingId, new SelectList(Model.Trainings, "Key", "Value"), new { @class = "custom dropdown", @style = "margin-bottom:10px" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.LabelFor(x => x.Training.TDString)
                        </td>
                        <td>
                            @Html.TextBoxFor(x => x.Training.TDString, new { @class = "datetime" })
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2" style="text-align: right">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <input type="reset" value="Clear" class="btn btn-primary" />
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        
    }
</div>

trunk/DMP/DMP/Views/Dealer/UploadFile.cshtml
@model DMP.Models.FileUploadModel
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 class="subheader">
    UploadFile</h4>
<div class="row">
    @using (Html.BeginForm("UploadFile", "Dealer", FormMethod.Post, new { enctype = "multipart/form-data" })) {
        <div>
            <span>Upload</span> <span>
                <input type="file" name="File" id="upload_file" />
            </span>
        </div>
        <div id="audit_mapbtndiv">
            <input type="submit" value="Upload" id="upload_btn" class="radius button" />
        </div>
        <span style="color: Red" id="err_msg">@Html.ValidationMessage("error")</span>
    }
</div>