trunk/DMP/DMP/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMP.Models;
using DMP.ModelsView;
using DMP.Repository;
using DMP.Services;
using DMP.Services.Interface;

namespace DMP.Controllers {

    [Authorize(Roles = "HQ,HQR")]
    public class MasterController : Controller {
        private readonly IMasterService masterService;
        private readonly ICompetencyProfileMapService competencyProfileMapService;
        private readonly ITrainingProfileMapService trainingProfileMapService;
        private readonly IDealerManpowerService dealerManpowerService;
        private readonly IUserService userService;
        private readonly IUserDealerMapService userDealerMapService;

        public MasterController(IMasterService masterService, ICompetencyProfileMapService competencyProfileMapService, ITrainingProfileMapService trainingProfileMapService, IDealerManpowerService dealerManpowerService, IUserService userService, IUserDealerMapService userDealerMapService) {
            this.masterService = masterService;
            this.competencyProfileMapService = competencyProfileMapService;
            this.trainingProfileMapService = trainingProfileMapService;
            this.dealerManpowerService = dealerManpowerService;
            this.userService = userService;
            this.userDealerMapService = userDealerMapService;
        }

        #region Regions

        public ActionResult Regions() {
            var model = new RegionViewModel {
                Regions = masterService.GetAllRegions().Select(RegionModel.FromDomainModel).ToList()
            };
            ViewBag.List = Session["BreadcrumbList"];
            return View(model);
        }

        public ActionResult EditRegion(int id) {
            var model = id > 0 ? RegionModel.FromDomainModel(masterService.GetRegion(id)) : new RegionModel();
            return PartialView("EditRegion", model);
        }

        [HttpPost]
        public void EditRegion(RegionModel model) {
            if (ModelState.IsValid) {
                var region = RegionModel.ToDomainModel(model);
                if (region.Id > 0) {
                    masterService.UpdateRegion(region);
                } else {
                    masterService.AddRegions(new[] { region });
                }
            }
            //return RedirectToAction("Regions");
        }

        public ActionResult DeleteRegion(int id) {
            masterService.DeleteRegion(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region State

        public ActionResult States() {
            var states = masterService.GetAllStates().Select(StateModel.FromDomainModel).ToList();
            ViewBag.List = Session["BreadcrumbList"];
            return View(states);
        }

        public ActionResult EditState(int id) {
            var state = id > 0 ? StateModel.FromDomainModel(masterService.GetState(id)) : new StateModel();
            var model = new StateViewModel {
                State = state,
                Regions = masterService.GetAllRegions().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)).ToList()
            };
            return PartialView("EditState", model);
        }

        [HttpPost]
        public void EditState(StateViewModel model) {
            if (!ModelState.IsValid) {
                return;
            }
            var state = StateModel.ToDomainModel(model.State);
            if (state.Id > 0) {
                masterService.UpdateState(state);
            } else {
                masterService.AddStates(new[] { state });
            }
        }

        public ActionResult DeleteState(int id) {
            masterService.DeleteState(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region ProductCategory

        public ActionResult Categories() {
            var model = new ProductCategoryViewModel {
                Categories = masterService.GetAllCategories().Select(ProductCategoryModel.FromDomainModel).ToList()
            };
            ViewBag.List = Session["BreadcrumbList"];
            return View(model);
        }

        public ActionResult EditCategory(int id) {
            var model = id > 0
                          ? ProductCategoryModel.FromDomainModel(masterService.GetProductCategory(id))
                          : new ProductCategoryModel();
            return PartialView("EditCategory", model);
        }

        [HttpPost]
        public void EditCategory(ProductCategoryModel model) {
            if (!ModelState.IsValid) {
                return;
            }
            var category = ProductCategoryModel.ToDomainModel(model);
            if (category.Id > 0) {
                masterService.UpdateCategory(category);
            } else {
                masterService.AddCategory(new[] { category });
            }
        }

        public ActionResult DeleteCategory(int id) {
            masterService.DeleteCategory(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Product

        public ActionResult Products() {
            var products = masterService.GetAllProducts().Select(ProductModel.FromDomainModel).ToList();
            ViewBag.List = Session["BreadcrumbList"];
            return View(products);
        }

        public ActionResult EditProduct(int id) {
            var product = id > 0 ? ProductModel.FromDomainModel(masterService.GetProduct(id)) : new ProductModel();
            var model = new ProductViewModel {
                Product = product,
                Categories = masterService.GetAllCategories().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)).ToList()
            };
            return PartialView("EditProduct", model);
        }

        [HttpPost]
        public void EditProduct(ProductViewModel model) {
            var product = ProductModel.ToDomainModel(model.Product);
            if (product.Id > 0) {
                masterService.UpdateProduct(product);
            } else {
                masterService.AddProduct(new[] { product });
            }
        }

        public ActionResult DeleteProduct(int id) {
            masterService.DeleteProduct(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region ProductVarient

        public ActionResult Varients() {
            var varients = masterService.GetAllProductVarients().Select(ProductVarientModel.FromDomainModel).ToList();
            ViewBag.List = Session["BreadcrumbList"];
            return View(varients);
        }

        public ActionResult EditVarient(int id) {
            var varient = id > 0
                            ? ProductVarientModel.FromDomainModel(masterService.GetProductVarient(id))
                            : new ProductVarientModel();
            var model = new ProductVarientViewModel {
                ProductVarient = varient,
                Products = masterService.GetAllProducts().Select(x => new KeyValuePair<int, string>(x.Id, x.Name)).ToList()
            };
            return PartialView("EditVarient", model);
        }

        [HttpPost]
        public void EditVarient(ProductVarientViewModel model) {
            if (!ModelState.IsValid) {
                return;
            }
            var varient = ProductVarientModel.ToDomainModel(model.ProductVarient);
            if (varient.Id > 0) {
                masterService.UpdateProductVarient(varient);
            } else {
                masterService.AddProductVarient(new[] { varient });
            }
        }

        public ActionResult DeleteVarient(int id) {
            masterService.DeleteProductVarient(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Training

        public ActionResult Trainings() {
            var trainings = masterService.GetAllTrainings().Select(TrainingModel.FromDomainModel).ToList();
            ViewBag.List = Session["BreadcrumbList"];
            return View(trainings);
        }

        public ActionResult EditTraining(int id) {
            var model = new TrainingViewModel {
                Designations = Enumeration.GetAll<Designation>(),
                Training = id > 0 ? TrainingModel.FromDomainModel(masterService.GetTraining(id)) : new TrainingModel()
            };
            return PartialView("EditTraining", model);
        }

        [HttpPost]
        public void EditTraining(TrainingViewModel model) {
            if (!ModelState.IsValid) {
                return;
            }
            var training = TrainingModel.ToDomainModel(model.Training);
            if (training.Id > 0) {
                masterService.UpdateTraining(training);
            } else {
                masterService.AddTraining(new[] { training });
                //Add New Training to TrainingProfileMap
                var manpowerIds =
                    dealerManpowerService.GetAllDealerManpowers().Select(x => x.Id);
                var list = manpowerIds.Select(id => new TrainingProfileMap() { Id = 0, TrainingId = training.Id, DealerManpowerId = id }).ToList();
                trainingProfileMapService.AddTrainingProfileMap(list);
            }
        }

        public ActionResult DeleteTraining(int id) {
            masterService.DeleteTraining(id);
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Dealer

        public ActionResult Dealers() {
            var dealers = masterService.GetAllDealers().Select(DealerModel.FromDomainModel).ToList();
            ViewBag.List = Session["BreadcrumbList"];
            return View(dealers);
        }

        public ActionResult EditDealer(int id) {

trunk/DMP/DMP/Views/Shared/ChangeCredential.cshtml
@model DMP.Models.ChangePasswordModel
@using DMP.Utils
<div class="row-fluid">
    <div class="span4 offset4">
        @using (Ajax.BeginForm(new AjaxOptions { OnComplete = "closePopUp()" })) {
            <div class="panel">
                <div>@Html.LabelFor(x => x.OldPassword)
                    @Html.EditorFor(x => x.OldPassword)
                </div>
                <div>@Html.LabelFor(x => x.NewPassword)
                    @Html.EditorFor(x => x.NewPassword)
                </div>
                <div>@Html.LabelFor(x => x.ConfirmPassword)
                    @Html.EditorFor(x => x.ConfirmPassword)
                </div>
                <div>
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

trunk/DMP/DMP/Views/Shared/ProductStatPartial.cshtml
@model IEnumerable<DMP.Models.ProductStatModel>
<div>
    <div class="span4" id="dvCompetency">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th colspan=@(Model.Count()) class="centerHead1">
                        Competency
                    </th>
                </tr>
                <tr>
                    @foreach (var product in Model) {
                        <th class="centerHead2">@product.Product
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (var competency in Model) {
                        <td class="data1">@competency.Competency %
                        </td>
                    }
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan=@(Model.Count()) class="foot1">
                        @Model.Average(x => x.Competency).ToString("#.##") %
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="span4" id="dvProductivity">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th colspan=@(Model.Count()) class="centerHead1">
                        Productivity
                    </th>
                </tr>
                <tr>
                    @foreach (var product in Model) {
                        <th class="centerHead2">@product.Product
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (var productivity in Model) {
                        <td class="data1">@productivity.Productivity 
                        </td>
                    }
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan=@(Model.Count()) class="foot1">
                        @Model.Average(x => x.Productivity).ToString("#.##") .
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="span4" id="dvAttrition">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th colspan=@(Model.Count()) class="centerHead1">
                        Attrition
                    </th>
                </tr>
                <tr>
                    @foreach (var product in Model) {
                        <th class="centerHead2">@product.Product
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach (var attrition in Model) {
                        <td class="data1">@attrition.Attrition %
                        </td>
                    }
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan=@(Model.Count()) class="foot1">
                        @Model.Average(x => x.Attrition).ToString("#.##") %
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

trunk/DMP/DMP/Views/Shared/ReportManpowerPartial.cshtml
@model DMP.ModelsView.ReportManpowerViewModel
@using DMP.Utils
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th colspan=@(Model.Products.Count() * 2 + 6) class="head1">
                Manpower - Plan Vs Actual
            </th>
        </tr>
        <tr>
            @if (Model.ReportManpowers.Any() && Model.ReportManpowers.First().User != null) {
                <th class="head2">
                </th>
            }
            @foreach (var product in Model.Products) {
                <th colspan="2" class="head2">@product
                </th>
            }
            <th colspan="2" class="head2">
                Total
            </th>
            <th colspan="3" class="head2">
                DDC Training
            </th>
        </tr>
        <tr>
            @if (Model.ReportManpowers.Any() && Model.ReportManpowers.First().User != null) {
                <th class="head3">
                </th>
            }
            @foreach (var product in Model.Products) {
                <th class="head3">
                    Plan
                </th>
                <th class="head3">
                    Actual
                </th>
            }
            <th class="head3">
                Plan
            </th>
            <th class="head3">
                Actual
            </th>
            @foreach (var level in Model.TrainingLevels) {
                if (@level != "None")
                {       <th class="head3">@level
                     </th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var reportItem in Model.ReportManpowers) {
            <tr>
                @if (reportItem.User != null) {
                    <td>
                        <a href=@reportItem.UserUrl class="user">@reportItem.User</a>
                    </td> 
                }
                @foreach (var plan in reportItem.Manpowers) {
                    <td class="data1">@plan.Plan
                    </td>
                    <td class="data1">@plan.Actual
                    </td>
                }
                <td class="data1">@reportItem.Manpowers.Sum(x => x.Plan)
                </td>
                <td class="data1">@reportItem.Manpowers.Sum(x => x.Actual)
                </td>
                @foreach (var level in reportItem.TrainingLevels)
                {
                    if (@level.Level != "None")
                    {
                        <td class="data1">@level.LevelCount
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

trunk/DMP/DMP/Views/Shared/ReportMenuPartial.cshtml
@*<div class="well side-nav">
    <ul class="nav nav-list">
        @if (User.IsInRole("HQ")) {
            <li><a href="#">Retail Trend</a></li>
            <li><a href="#">RM Dashbaoard</a></li>
            <li><a href="#">RM Wise DSE Incentive</a></li>
            <li><a href="#">Attrition Analysis</a></li>
        } else if (User.IsInRole("RM")) {
            <li><a href="#">RSMs Retail Trend</a></li>
            <li><a href="#">RSM Dashbaoard</a></li>
            <li><a href="#">RSM Wise DSE Incentive</a></li>
            <li><a href="#">Attrition Analysis</a></li>
            <li><a href="#">State Retail Trend</a></li>
            <li><a href="#">State Dashbaoard</a></li>
            <li><a href="#">State Wise DSE Incentive</a></li>
            <li><a href="#">State Wise Attrition Analysis</a></li>
        } else if (User.IsInRole("RSM")) {
            <li><a href="#">CSMs Retail Trend</a></li>
            <li><a href="#">CSM Dashbaoard</a></li>
            <li><a href="#">CSM Wise DSE Incentive</a></li>
            <li><a href="#">Attrition Analysis</a></li>
            <li><a href="#">State wise retail trend</a></li>
        } else if (User.IsInRole("CSM")) {
            <li><a href="#">Dealer Retail Trend</a></li>
            <li><a href="#">Dealer Dashbaoard</a></li>
            <li><a href="#">DSE Incentive</a></li>
            <li><a href="#">Attrition Analysis</a></li>
            <li><a href="#">Monthly Productivity</a></li>
        }
    </ul>
</div>*@
<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th class="head1">
                    <img src="../../Images/Reports.png" />
                    Reports
                </th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Role == "HQ") {
                <tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">Retail Trend</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/Dashboard.png" class="img1" />
                        <a href="#">Dashbaoard</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/incentive.png" class="img1" />
                        <a href="#">Region Wise DSE Incentive</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/attrition.png" class="img1" />
                        <a href="#">Attrition Analysis</a>
                    </td>
                </tr>
            } else if (ViewBag.Role == "RM") {
                <tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">Retail Trend</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/Dashboard.png" class="img1" />
                        <a href="#">Dashbaoard</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/incentive.png" class="img1" />
                        <a href="#">Incentives</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/attrition.png" class="img1" />
                        <a href="#">Attrition Analysis</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">State Wise Retail Trend</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/Dashboard.png" class="img1" />
                        <a href="#">State Wise Dashbaoard</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/incentive.png" class="img1" />
                        <a href="#">State Wise DSE Incentive</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/attrition.png" class="img1" />
                        <a href="#">State Wise Attrition Analysis</a>
                    </td>
                </tr>
            } else if (ViewBag.Role == "RSM") {
                <tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">Retail Trend</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/Dashboard.png" class="img1" />
                        <a href="#">Dashbaoard</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/incentive.png" class="img1" />
                        <a href="#">Incentives</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/attrition.png" class="img1" />
                        <a href="#">Attrition Analysis</a>
                    </td>
                </tr>
@*<tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">State wise retail trend</a>
                    </td>
                </tr>*@
            } else if (ViewBag.Role == "CSM") {
                <tr>
                    <td class="row1">
                        <img src="../../Images/trend_report.png" class="img1" />
                        <a href="#">Retail Trend</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/Dashboard.png" class="img1" />
                        <a href="#">Dashbaoard</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/incentive.png" class="img1" />
                        <a href="#">Incentives</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/attrition.png" class="img1" />
                        <a href="#">Attrition Analysis</a>
                    </td>
                </tr>
                <tr>
                    <td class="row1">
                        <img src="../../Images/productivity.png" class="img1" />
                        <a href="#">Monthly Productivity</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

trunk/DMP/DMP/Views/Shared/ResetPassword.cshtml
@model DMP.Models.ResetPasswordModel
@using DMP.Utils
<script src = "@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src = "@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnSubmit').bind('click', function (e) {
            if (!validation()) {
                e.preventDefault();
            }
        });
        function validation() {
            $('#txtPwd').removeClass('inputError');
            $('#pwdMsg').html('').hide();
            $('#txtCnfPwd').removeClass('inputError');
            $('#cnfPwdMsg').html('').hide();
            var pwd = $('#txtPwd').val();
            var cnfPwd = $('#txtCnfPwd').val();
            if (pwd.indexOf(' ') >= 0) {
                $('#txtPwd').addClass('inputError');
                $('#pwdMsg').html('Password is not in correct format').show();
                return false;
            } else if (pwd.length < 6) {
                $('#txtPwd').addClass('inputError');
                $('#pwdMsg').html('Password must be of min 6 characters').show();
                return false;
            } else if (pwd.toLowerCase().trim() != cnfPwd.toLowerCase().trim()) {
                $('#txtCnfPwd').addClass('inputError');
                $('#cnfPwdMsg').html('Password not matched').show();
                return false;
            }
            return true;
        }
    });
</script>
<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnComplete = "closePopUp()" })) {
        <div style="width: 100%">
            @Html.HiddenFor(x => x.Id)
            <div>
                @Html.LabelFor(x => x.Password)
                @Html.PasswordFor(x => x.Password, new { @id = "txtPwd" })
                <span id="pwdMsg" style="display: none; color: red; font-size: 12px;"></span>
            </div>
            <div>@Html.LabelFor(x => x.ConfirmPassword)
                @Html.PasswordFor(x => x.ConfirmPassword, new { @id = "txtCnfPwd" })
                <span id="cnfPwdMsg" style="display: none; color: red; font-size: 12px;"></span>
            </div>
            <div>
                <input type="submit" value="Save" class="btn btn-primary" id="btnSubmit" />
                <input type="reset" value="Reset" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

trunk/DMP/DMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" content="text/html; charset=UTF-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Assets/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src = "@Url.Content("~/Scripts/jquery-1.8.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Assets/bootstrap/js/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.tmpl.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout-2.1.0.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout-map.js")" type="text/javascript"></script>
</head>
<body>
    <div class="row-fluid">
        <div class="span3">
            <a href="/Home/Index">
                <img class="brand" src="~/Images/ETB_logo.jpg" />
            </a>
        </div>
        <div class="span6">
            @Html.Action("LogOnPartial", "Account")
        </div>
        <div class="span3" style="float: right; margin-top: 5px; text-align: right; margin-bottom: 5px;">
            <div style="margin-left: 10px; margin-right: 15px; margin-left: 10px">
                <a href="/Home/Index">
                    <img class="brand" src="~/Images/logo.png" /></a>
            </div>
        </div>
    </div>
    <div class="navbar navbar-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                @*<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar collapsed">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar">
                    </span></a>*@
                <div class="nav-collapse collapse" style="height: 0px;">
                    @if (User.IsInRole("HQ") || User.IsInRole("HQR")) {
                        <ul class="nav">
                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Setting<b
                                class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Region", "Regions", "Master")</li>
                                    <li>@Html.ActionLink("State", "States", "Master")</li>
                                    <li>@Html.ActionLink("Dealer", "Dealers", "Master")</li>
                                    <li>@Html.ActionLink("Category", "Categories", "Master")</li>
                                    <li>@Html.ActionLink("Segment", "Products", "Master")</li>
                                    <li>@Html.ActionLink("Product", "Varients", "Master")</li>
                                    <li>@Html.ActionLink("Other Trainings", "Trainings", "Master")</li>
                                    <li>@Html.ActionLink("Attrition", "Attrition", "Master")</li>
                                    <li>@Html.ActionLink("Competency", "Competency", "Master")</li>
                                    <li>@Html.ActionLink("Special Schemes", "SpecialSchemes", "Master")</li>
                                    <li>@Html.ActionLink("Users", "Users", "Account")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Manpower", "ManpowerTargets", "Dealer")</li>
                        </ul>
                       
                    }
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div style="margin: 5px 10px 5px 20px">
            @if (ViewBag.List != null) {
                @Html.Partial("breadcrumbs", (object)ViewBag.List)
            }
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
        <div class="clear">
        </div>
    </div>
    @*<div id="footer">
        <div class="container">
            <div class="span4 offset3">
                <img src="~/Images/volvo-logo1.png" style="position: absolute; bottom: 0; padding: 10px" />
            </div>
        </div>
    </div>*@
    <script src = "@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src = "@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src = "@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src = "@Url.Content("~/Scripts/common.js")" type="text/javascript"></script>
</body>
</html>